const operatorMessages: Record<string, string> = {
  "Failed to fetch": "无法连接 CPA",
  "invalid management key": "Management Key 无效",
  "management key is unavailable": "Management Key 不可用",
  "preview expired; create a new preview": "预览已过期，请重新生成",
  "preview not found": "预览不存在，请重新生成",
  "preview contains no eligible targets": "预览中没有可执行账号",
  "a batch job is already running": "已有批量任务正在运行",
  "no failed targets are available to retry": "没有可重试的失败项",
  "failed to load accounts": "账号列表加载失败",
  "failed to resolve target accounts": "目标账号解析失败",
  "failed to export accounts": "账号导出失败",
  "runtime-only account has no physical auth file": "运行时账号没有物理 Auth 文件",
  "account is not backed by an editable auth file": "账号没有可编辑的 Auth 文件",
  "account has no stable auth index": "账号缺少稳定索引",
  "backing auth file is not JSON": "Auth 文件不是 JSON",
  "multiple runtime accounts share this source file": "多个运行时账号共享同一来源文件",
  "physical auth file is unavailable": "物理 Auth 文件不可用",
  "physical auth file is invalid": "物理 Auth 文件无效",
  "target resolves to a duplicate physical auth file": "目标指向重复的物理 Auth 文件",
  "account no longer exists": "账号已不存在",
  "job was interrupted before this target was updated": "账号更新前任务已中断",
  "unexpected worker failure": "任务工作线程异常",
  "physical auth file could not be re-read": "无法重新读取物理 Auth 文件",
  "physical auth file changed after preview": "物理 Auth 文件在预览后已变化",
  "job was interrupted during the update": "账号更新过程中任务已中断",
  "account field update failed": "账号字段更新失败",
  "account disabled-state update failed": "账号启用状态更新失败",
  "account disabled-state update failed after other fields were applied": "其他字段已生效，但账号启用状态更新失败",
  "plugin stopped before this target completed": "该账号完成前插件已停止",
  "provider reported an account error": "Provider 报告账号异常",
  unauthorized: "未授权",
  payment_required: "需要付费或额度不足",
  not_found: "上游资源不存在",
  "quota exhausted": "额度已用尽",
  "transient upstream error": "上游临时异常",
  "request failed": "请求失败",
  "cloudflare challenge": "触发 Cloudflare 验证",
  invalid_grant: "授权已失效",
  "disabled via management api": "已通过 Management API 禁用",
  "removed via management api": "已通过 Management API 移除",
  "upstream temporarily unavailable": "上游暂时不可用",
};

export function operatorMessage(message?: string): string {
  const normalized = message?.trim() ?? "";
  return operatorMessages[normalized] ?? normalized;
}
